// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "spamton  new":return img`
........................................
........................................
........................................
........................................
........................................
.........dd.......ddddddd...............
.........dfdddddddfffffffdd.............
..........dffffffffffffffffd............
.........ddddfffffffffffffffd...........
.........dffffffffffffffffffd...........
..........ddfffff11111111ffd............
...........ddfff111111111df.............
..........dffff111ffff1ffff.............
...........ddff11f5555f3333f............
.............dffff5555f3333f............
.............ff11f5555f3333f............
.............f1111ffff1ffff.............
.............f11122111111ff2d...........
..........dd.f1112f1111111111dd.........
.........dffdfff11ff11111111111dd.......
.........ddffffff11fffffffffdddddd......
...........dfffff11f1111f11d............
............dfffff11ffff11f.............
.............ddfff11f11f1ff.............
...............dfff1ffff1fd.............
..............dffff111111ffd............
..............dfffffffffffffd...........
.............dfffffd111dffffd...........
.............dffffffd1dffffffd..........
............dfffdffffdffffffffd.........
............dffddffffffffffdfffd........
...........dffd.dfffffffffd.df11dd......
..........d1dfd..dffffffffd..df11d......
.........d11fd...dfffffffd....ddd.......
.........dddd....dfffffffd..............
..................dfffffd...............
..................dfffffd...............
..................d1111fd...............
..................d11f1d................
...................d1f1d................
...................dddd.................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
